###########################################################
### Portfolio Website for Anshu Kale - Config File
###########################################################

############################
# --- Required options --- #
############################

# Website title
title: "Anshu Kale - Portfolio"

# Footer author name
author: "Anshu Kale"

###############################################
# --- Navigation Bar Links (Updated) --- #
###############################################

navbar-links:
  Home: "index"
  About Me: "aboutme"
  Projects: "projects"
  Contact: "contact"

################
# --- Logo --- #
################

# Profile image in the navbar (Upload your own image in `/assets/img/`)
avatar: "/assets/img/Profile.jpg"
round-avatar: true  # Keeps profile image circular

# If you have a banner background, upload it to `/assets/img/`
banner: "/assets/img/banner.jpg"

#####################################
# --- Footer Social Media Links --- #
#####################################

social-network-links:
  email: "anshukale1718@gmail.com"
  github: "anshukale"
  linkedin: "anshu-kale"
  twitter: "your-twitter-handle"  # Optional
  kaggle: "your-kaggle-username"  # Optional
  stackoverflow: "your-stackoverflow-id"  # Optional

###########################
# --- General Options --- #
###########################

share-links-active:
  twitter: true
  facebook: false
  linkedin: true

# Add website title to every page title
title-on-all-pages: true

# SEO-friendly URL formatting
url-pretty: "anshukale.github.io"

# Excerpt word length for blog previews
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true

# Enable search bar in navbar
post_search: true

# Add an "Edit on GitHub" button in footer
edit_page_button: false

######################################
# --- Theme Colors (Customize) --- #
######################################

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"

###########################
# --- Web Analytics --- #
###########################

# Google Analytics (Optional)
#gtag: "G-XXXXXXXXXX"

####################
# --- Comments --- #
####################

# If you want to add comments to blog posts, enable one of these:
#disqus: "your-disqus-shortname"
#giscus:
#  repository: "anshukale/portfolio"

################
# --- Misc --- #
################

timezone: "Asia/Kolkata"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  -
    scope:
      path: ""
    values:
      layout: "page"

# Exclude these files from production
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
